config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :commentable do
    resources :comments, only: [:create, :edit, :update, :destroy], concerns: :votable
  end

  concern :votable do
    patch :vote_up, on: :member, controller: :votes
    patch :vote_down, on: :member, controller: :votes
  end

  resources :questions, concerns: [:commentable, :votable], shallow: true do
    resources :answers, only: [:new, :create, :edit, :update, :destroy],
                        shallow: true,
                        concerns: [:commentable, :votable] do
      post "mark_best", on: :member
    end

    collection do
      get "popular(/page/:page)" => "questions#popular", as: :popular
      get "unanswered(/page/:page)" => "questions#unanswered", as: :unanswered
      get "active(/page/:page)" => "questions#active", as: :active
      get "tagged/:tag(/page/:page)" => "questions#tagged", as: :tagged
    end

    post "add_favorite" => "questions#add_favorite", as: :add_favorite
    post "remove_favorite" => "questions#remove_favorite", as: :remove_favorite
  end

  resources :tags, only: :index do
    collection do
      get "/(page/:page)", to: "tags#index"
      get "/newest(/page/:page)", to: "tags#newest", as: :newest
      get "/popular(/page/:page)", to: "tags#popular", as: :popular
    end
  end

  resources :attachments, only: [:destroy]

  resources :users, only: [:index, :show, :edit, :update], param: :username do
    get "/logins" => "users#logins", as: :logins, on: :member

    collection do
      get "/by_registration(/page/:page)", to: "users#by_registration", as: :by_registration
      get "/alphabetically(/page/:page)", to: "users#alphabetically", as: :alphabetically
    end
  end

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
      resources :users, only: [:index, :show], param: :username
      get "/profile", to: "users#profile", as: :profile
    end
  end

  root "questions#index"
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  votes      :integer          default(0), not null
#

class Question < ApplicationRecord
  include Votable

  default_scope { order(created_at: :desc) }

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :favorite_questions, dependent: :destroy
  has_many :favorites, through: :favorite_questions, source: :user
  has_many :impressions, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  accepts_nested_attributes_for :attachments, reject_if: :no_attachment

  validates :body, presence: true, length: { in: 10..5000 }
  validates :tag_list, presence: true
  validates :title, presence: true, length: { in: 5..512 }

  before_save :set_recent_activity
  after_create :subscribe_author_to_question

  scope :active, -> { unscoped.order("recent_activity DESC, created_at DESC") }
  scope :popular, -> { unscoped.order("votes_sum DESC, created_at DESC") }
  scope :tagged, ->(tag) { unscoped.joins(:tags).where("tags.name = ?", tag) }
  scope :unanswered, -> { where("answers_count = 0") }

  paginates_per 10

  def best_answer?
    answers.find_by(best: true) ? true : false
  end

  def tag_list
    tags.map(&:name).join(",")
  end

  def tag_list=(list)
    list ||= ""
    names = list.split(",").map { |n| n.strip.downcase.tr(" ", "-") }.uniq
    self.tags = names.map { |name| Tag.find_or_create_by(name: name) }
  end

  private

  def set_recent_activity
    self.recent_activity = Time.zone.now
  end

  def no_attachment(attrs)
    attrs["file"].blank? && attrs["file_cache"].blank?
  end

  def subscribe_author_to_question
    user.add_favorite(id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    respond_with @questions = Question.all, each_serializer: QuestionsSerializer
  end

  def show
    respond_with @question = Question.find(params[:id])
  end

  def create
    respond_with @question = current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :tag_list)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :update, :destroy, :add_favorite, :remove_favorite]
  before_action :set_question, only: [:show, :edit, :update, :destroy, :add_favorite, :remove_favorite]
  before_action :add_user_id_to_attachments, only: [:create, :update]
  after_action :updated_edited, only: :update

  respond_to :html, except: [:update, :add_favorite, :remove_favorite]
  respond_to :json, only: [:update, :add_favorite, :remove_favorite]

  authorize_resource

  def index
    respond_with @questions = Question.page(params[:page])
  end

  def popular
    @questions = Question.popular.page(params[:page])
    render :index
  end

  def unanswered
    @questions = Question.unanswered.page(params[:page])
    render :index
  end

  def active
    @questions = Question.active.page(params[:page])
    render :index
  end

  def tagged
    @questions = Question.tagged(params[:tag]).page(params[:page])
    render :index
  end

  def new
    @question = Question.new
    @attachment = @question.attachments.build
  end

  def show
    @answers = @question.answers
    @comments = @question.comments
    @question.impressions.find_or_create_by(remote_ip: request.remote_ip,
                                            user_agent: (request.user_agent || "no user_agent"))
  end

  def create
    respond_with @question = current_user.questions.create(question_params)
  end

  def update
    update_resource @question
  end

  def destroy
    respond_with @question.destroy
  end

  def add_favorite
    current_user.add_favorite(@question.id)
    render json: favorite_json, status: 200
  end

  def remove_favorite
    current_user.remove_favorite(@question.id)
    render json: favorite_json, status: 200
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :tag_list,
                                     attachments_attributes: [:file, :file_cache, :user_id, :_destroy])
  end

  def set_question
    @question = Question.find(params[:question_id] || params[:id])
  end

  def updated_edited
    @question.update(edited_at: Time.zone.now) unless @question.errors.any?
  end

  def favorite_json
    { status: "success", count: @question.favorites.count, id: @question.id }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def active?(page)
    "active" if params[:action] == page.to_s
  end
end

app/views/questions/_form.html.slim
= simple_form_for @question, remote: ((defined? remote) ? remote : false) do |f|
  = f.error_notification
  = f.input :title
  = f.input :body, input_html: { rows: 10 }
  = f.input :tag_list, label: "Tags"
  = f.simple_fields_for :attachments do |a|
    = a.label "Files (allowed formats: jpg, jpeg, gif, png)"
    |&nbsp;&nbsp;&nbsp;
    = link_to_add_association 'Add file', f, :attachments, data: {"association-insertion-node" => ".nested-fields:last", "association-insertion-method" => "after"}
    = render 'attachment_fields', f: a
  .form-group
    = f.button :submit, class: "btn btn-success"

app/views/questions/_question.html.slim
article.question.row id="question_#{question.id}"
  .col-md-3.row.stats
    .col-md-4
      .text-primary.text-center.question-votes
        strong #{question.votes_sum}
        br
        span votes
    .col-md-4
      .text-success.text-center.question-answers
        strong #{question.answers.count}
        br
        span answers
    .col-md-4
      .text-info.text-center.question-views
        strong #{question.impressions.count}
        br
        span views
  .col-md-9
    h3.question-title
      =link_to question.title, question
    .question-tags.pull-left
      - question.tags.each do |tag|
        = link_to tag.name, "/questions/tagged/#{tag.name}", class: "label label-default"
    .question-author.pull-right
      small
        | by
        = link_to question.user.username, user_path(question.user.username)
        |  #{time_ago_in_words(question.created_at)} ago

app/views/questions/index.html.slim
.row
  .col-md-10
    - unless params[:action] == "show_by_tag"
      ul.nav.nav-tabs.questions-sorting.pull-right
        li class=(active?(:index))
          = link_to "newest", root_path
        li class=(active?(:popular))
          = link_to "popular", "/questions/popular"
        li class=(active?(:active))
          = link_to "active", "/questions/active"
        li class=(active?(:unanswered))
          = link_to "unanswered", "/questions/unanswered"
.row
  .col-md-10
    = render @questions
    = paginate @questions
  .col-md-2
    = link_to "Ask a Question", new_question_path, class: "btn btn-primary ask-question"

app/views/questions/new.html.slim
= title "New Question"
.row
  .col-md-8.col-md-offset-2
    h2 Ask a Question
    = render "form"

app/views/questions/show.html.slim
= title @question.title
.row
  .col-md-12
    header class="page-header" id="question-title"
      h1.question-title = @question.title
.row
  .col-md-10
    .panel.panel-default.question data-question-id="#{@question.id}" data-author="#{@question.user.username}"
      .panel-body
        .row
          .col-md-1.question-voting
            .voting
              - if can?(:vote_up, @question)
                = link_to "", vote_up_question_path(@question), class: "vote-up", remote: true, data: { type: :json }, method: :patch
              - elsif @question.user_voted(current_user) == 1
                span.voted-up
              strong.votes = @question.votes_sum
              - if can?(:vote_down, @question)
                = link_to "", vote_down_question_path(@question), class: "vote-down", remote: true, data: { type: :json }, method: :patch
              - elsif @question.user_voted(current_user) == -1
                span.voted-down
            .favorite
              - if can?(:add_favorite, @question)
                -if current_user.favorite?(@question.id)
                  = link_to question_remove_favorite_path(@question), class: "remove-from-favorites", remote: true, data: { type: :json }, method: :post do
                    span.glyphicon.glyphicon-star.favorite-question title="You have already added this question to favorites!"
                -else
                  = link_to question_add_favorite_path(@question), class: "add-to-favorites", remote: true, data: { type: :json }, method: :post do
                    span.glyphicon.glyphicon-star-empty title="Add this question to your favorites!"
                div.counter#favorites-counter
                  = @question.favorites.count
          .col-md-11
            .question-body
              = @question.body
        .question-tags data-tags="#{@question.tag_list}"
          - @question.tags.each do |tag|
            = link_to tag.name, "/questions/?tag=#{tag.name}", class: "label label-default"
        .question-author.text-right
          small
            | by
            = link_to @question.user.username, user_path(@question.user.username)
            |  #{time_ago_in_words(@question.created_at)} ago
          div
            img src=(@question.user.avatar.tiny.url)
            br
            small
              = @question.user.reputation_sum
          - if @question.edited_at.to_s > @question.created_at.to_s
            small
              span.text-muted
                | edited
                = time_ago_in_words(@question.edited_at)
                |  ago
        - if @question.attachments.any?
          ul.question-attachments.attachments-list
            - @question.attachments.each do |a|
              li
                div
                  a href="#{a.file.url}" rel='shadowbox[question-attachments]'
                    = image_tag a.file.url
                  - if can?(:destroy, a)
                    = link_to a, method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: "delete-attachment" do
                      span.glyphicon.glyphicon-remove title="Remove attachment"
        .comments-wrapper
          - if @comments.size > 0
            ul.comments
              = render @comments
      .panel-footer
        ul.question-management
          - if can?(:edit, @question)
            li
              = link_to "#", class: "edit-question", id: "edit-question" do
                span.glyphicon.glyphicon-pencil
            li
              = link_to @question, class: "delete-question", id: "delete-question", method: :delete, data: { confirm: "Are you sure?" } do
                span.glyphicon.glyphicon-remove
          - if can?(:create, Comment)
            li
              = link_to "Comment", "#", class: "show-comment-form"
        .comment-form
          = render "comments/form", comment: Comment.new, commentable: @question

    .answers
      h3#answers-counter data-counter=(@answers.count) = pluralize(@answers.count, "Answer")
      = render @answers, best_answer: @question.best_answer?
    - if can?(:create, Answer)
      div
        h3 Post answer
        .row
          .col-md-10#new-answer-form
            = render "answers/form", answer: Answer.new
    - else
      div
        p #{link_to "Register", new_user_registration_path} or #{link_to "log in", new_user_session_path} to post an answer to this question.
  .col-md-2
    = link_to "Ask a Question", new_question_path, class: "btn btn-primary"

= subscribe_to "/questions/#{@question.id}"