config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :commentable do
    resources :comments, only: [:create, :edit, :update, :destroy], concerns: :votable
  end

  concern :votable do
    patch :vote_up, on: :member, controller: :votes
    patch :vote_down, on: :member, controller: :votes
  end

  resources :questions, concerns: [:commentable, :votable], shallow: true do
    resources :answers, only: [:new, :create, :edit, :update, :destroy],
                        shallow: true,
                        concerns: [:commentable, :votable] do
      post "mark_best", on: :member
    end

    collection do
      get "popular(/page/:page)" => "questions#popular", as: :popular
      get "unanswered(/page/:page)" => "questions#unanswered", as: :unanswered
      get "active(/page/:page)" => "questions#active", as: :active
      get "tagged/:tag(/page/:page)" => "questions#tagged", as: :tagged
    end

    post "add_favorite" => "questions#add_favorite", as: :add_favorite
    post "remove_favorite" => "questions#remove_favorite", as: :remove_favorite
  end

  resources :tags, only: :index do
    collection do
      get "/(page/:page)", to: "tags#index"
      get "/newest(/page/:page)", to: "tags#newest", as: :newest
      get "/popular(/page/:page)", to: "tags#popular", as: :popular
    end
  end

  resources :attachments, only: [:destroy]

  resources :users, only: [:index, :show, :edit, :update], param: :username do
    get "/logins" => "users#logins", as: :logins, on: :member

    collection do
      get "/by_registration(/page/:page)", to: "users#by_registration", as: :by_registration
      get "/alphabetically(/page/:page)", to: "users#alphabetically", as: :alphabetically
    end
  end

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
      resources :users, only: [:index, :show], param: :username
      get "/profile", to: "users#profile", as: :profile
    end
  end

  root "questions#index"
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :text
#  commentable_id   :integer
#  commentable_type :string
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  include Votable

  default_scope { order("created_at") }

  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, presence: true, length: { in: 10..5000 }

  after_save :update_question_activity

  private

  def update_question_activity
    commentable.class.name == "Question" ? commentable.save : commentable.question.save
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_parent
  before_action :set_comment, only: [:edit, :update, :destroy]
  after_action :publish, only: [:create, :destroy], unless: -> { Rails.env.production? }

  respond_to :json

  authorize_resource

  def create
    respond_with @comment = @parent.comments.create(comment_params.merge(user_id: current_user.id))
  end

  def update
    update_resource @comment
  end

  def destroy
    respond_with @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  # rubocop:disable LineLength
  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength
  def publish
    case params[:action]
    when "create"
      if @comment.valid?
        channel_params = { comment_create: CommentSerializer.new(@comment, root: false).to_json,
                           parent: @parent.class.name,
                           parent_id: (@parent.id unless @comment.errors.any?) }
      end
    when "destroy"
      channel_params = { comment_destroy: @comment.id,
                         parent: @comment.commentable.class.name,
                         parent_id: @comment.commentable.id }
    end
    PrivatePub.publish_to "/questions/#{@comment.commentable.class.name == 'Question' ? @comment.commentable.id : @comment.commentable.question.id}", channel_params
  end
end

app/views/comments/_comment.html.slim
li class="comment" id="comment_#{comment.id}"
  .row
    .col-md-1
      .voting
        - if can?(:vote_up, comment)
          = link_to vote_up_comment_path(comment), class: "vote-up", remote: true, data: { type: :json }, method: :patch do
            span.glyphicon.glyphicon-plus
        - elsif comment.user_voted(current_user) == 1
          span.voted-up
            span.glyphicon.glyphicon-plus
        strong.votes = comment.votes_sum
        - if can?(:vote_down, comment)
          = link_to vote_down_comment_path(comment), class: "vote-down", remote: true, data: { type: :json }, method: :patch do
            span.glyphicon.glyphicon-minus
        - elsif comment.user_voted(current_user) == -1
          span.voted-down
            span.glyphicon.glyphicon-minus
    .col-md-11
      span.comment-body
        = comment.body
      small.comment-poster
        | &mdash;
        = link_to comment.user.username, user_path(comment.user.username)
        |  #{time_ago_in_words(comment.created_at)} ago
        - if comment.updated_at.to_s > comment.created_at.to_s
          span.text-muted
            |  edited #{time_ago_in_words(comment.updated_at)} ago
        - if can?(:update, comment)
          = link_to "edit", "#", class: "edit-comment"
        - if can?(:destroy, comment)
          |
          = link_to "delete", comment, class: "delete-comment", method: :delete, data: { confirm: "Are you sure?", id: comment.id, type: "json" }, remote: true

app/views/comments/_form.html.slim
= simple_form_for [(comment.commentable || commentable), comment], html: { id: nil }, remote: true do |f|
  = f.error_notification
  = f.input :body, input_html: { rows: ((defined? rows) ? rows : 10) }, label: false
  = f.button :submit, class: "btn btn-primary"
  |&nbsp;&nbsp;
  a.cancel-comment href="#" Cancel