config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :commentable do
    resources :comments, only: [:create, :edit, :update, :destroy], concerns: :votable
  end

  concern :votable do
    patch :vote_up, on: :member, controller: :votes
    patch :vote_down, on: :member, controller: :votes
  end

  resources :questions, concerns: [:commentable, :votable], shallow: true do
    resources :answers, only: [:new, :create, :edit, :update, :destroy],
                        shallow: true,
                        concerns: [:commentable, :votable] do
      post "mark_best", on: :member
    end

    collection do
      get "popular(/page/:page)" => "questions#popular", as: :popular
      get "unanswered(/page/:page)" => "questions#unanswered", as: :unanswered
      get "active(/page/:page)" => "questions#active", as: :active
      get "tagged/:tag(/page/:page)" => "questions#tagged", as: :tagged
    end

    post "add_favorite" => "questions#add_favorite", as: :add_favorite
    post "remove_favorite" => "questions#remove_favorite", as: :remove_favorite
  end

  resources :tags, only: :index do
    collection do
      get "/(page/:page)", to: "tags#index"
      get "/newest(/page/:page)", to: "tags#newest", as: :newest
      get "/popular(/page/:page)", to: "tags#popular", as: :popular
    end
  end

  resources :attachments, only: [:destroy]

  resources :users, only: [:index, :show, :edit, :update], param: :username do
    get "/logins" => "users#logins", as: :logins, on: :member

    collection do
      get "/by_registration(/page/:page)", to: "users#by_registration", as: :by_registration
      get "/alphabetically(/page/:page)", to: "users#alphabetically", as: :alphabetically
    end
  end

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
      resources :users, only: [:index, :show], param: :username
      get "/profile", to: "users#profile", as: :profile
    end
  end

  root "questions#index"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string           default(""), not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  default_scope { by_reputation }

  has_many :answers, dependent: :destroy
  has_many :attachments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_questions, dependent: :destroy
  has_many :favorites, through: :favorite_questions, source: :question
  has_many :identities, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :reputations, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :age, numericality: { only_integer: true }, allow_blank: true
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { in: 3..64 },
                       format: { with: /\A[\w\d_]+\z/,
                                 message: "allows only latin letters, numbers, and underscore." }

  def after_confirmation
    regular!
  end
  after_update :set_pending_status

  scope :by_reputation, -> { order("reputation_sum DESC") }
  scope :by_registration, -> { unscoped.order(created_at: :desc) }
  scope :alphabetically, -> { unscoped.order("username ASC") }

  enum status: { guest: 0, without_email: 1, pending: 2, regular: 3, admin: 99 }

  mount_uploader :avatar, AvatarUploader
  paginates_per 28

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :twitter, :vkontakte, :github]

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { in: 3..64 },
                       format: { with: /\A[\w\d_]+\z/,
                                 message: "allows only latin letters, numbers, and underscore." }
  validates :age, numericality: { only_integer: true }, allow_blank: true

  mount_uploader :avatar, AvatarUploader

  def to_param
    username
  end

  def favorite?(question_id)
    favorite_ids.include?(question_id) if question_id
  end

  def add_favorite(question_id)
    favorite_questions.create(question_id: question_id) if question_id
  end

  def remove_favorite(question_id)
    favorite_questions.find_by(question_id: question_id).destroy if question_id && favorite?(question_id)
  end

  def reputations_chart_data
    @reputations ||= ReputationChartService.new(self, 30).chart
  end

  def self.find_for_oauth(auth)
    identity = Identity.find_by(provider: auth.provider, uid: auth.uid)
    return identity.user if identity

    username = "#{auth.provider}_#{auth.uid}"
    user = User.new(email: "#{username}@stackdownflow.dev", username: username, password: Devise.friendly_token)
    user.skip_confirmation!
    user.status = "without_email"
    user.save!
    user.identities.create(provider: auth.provider, uid: auth.uid)
    user
  end

  def self.send_daily_digest
    questions = Question.where("created_at >= ?", 1.day.ago).to_a

    find_each do |user|
      DailyMailer.digest(user, questions).deliver
    end
  end

  private

  def set_pending_status
    return unless unconfirmed_email_changed? && !unconfirmed_email.nil?
    clear_changes_information
    pending!
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  authorize_resource

  def index
    respond_with @users = User.where("id != ?", current_resource_owner.id), each_serializer: UsersSerializer
  end

  def show
    respond_with @user = User.find_by(username: params[:username])
  end

  def profile
    respond_with current_resource_owner
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :logins]
  before_action :set_user

  respond_to :json, :html

  authorize_resource id_param: :username

  def index
    respond_with @users = User.page(params[:page])
  end

  def by_registration
    @users = User.by_registration.page(params[:page])
    render :index
  end

  def alphabetically
    @users = User.alphabetically.page(params[:page])
    render :index
  end

  def show
    respond_with @user
  end

  def edit; end

  def update
    update_resource @user
  end

  def logins
    authorize! :logins, @user
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :username, :email, :website, :age, :location, :full_name)
  end

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/views/users/_navigation.html.slim
.row
  .col-md-6
    - if params[:action] == "show"
      h4 #{@user.username}
    - else
      h4
        = link_to @user.username, @user
        |  > #{params[:action].capitalize}
  - if can?(:edit, @user)
    .col-md-6
        ul.nav.nav-tabs
          li class=("active" if params[:action] == "edit")
            = link_to "edit", edit_user_path(current_user), id: "edit-profile"
          li class=("active" if params[:action] == "logins")
            = link_to "my logins", logins_user_path(current_user)

app/views/users/edit.html.slim
= render "navigation"
.row
  .col-md-6.row.user-info
    .col-md-4
      img.user-avatar src=(@user.avatar.small.url)
      .text-center
        a#change-avatar href="#" change avatar
      = simple_form_for @user, remote: true, data: { type: :json }, html: {class: "change-avatar-form"} do |f|
        = hidden_field_tag :authenticity_token, form_authenticity_token
        = f.input :avatar
    .col-md-8
      = simple_form_for @user do |f|
        = f.input :username
        = f.input :email
        = f.input :website
        = f.input :location
        = f.input :age
        = f.input :full_name
        = f.submit class: "btn btn-success"
  .col-md-6

app/views/users/index.html.slim
= title "Users"

.row
  .col-md-10
    ul.nav.nav-tabs.questions-sorting.pull-right
      li class=(active?(:index))
        = link_to "by reputation", users_path
      li class=(active?(:alphabetically))
        = link_to "alphabetically", "/users/alphabetically"
      li class=(active?(:by_registration))
        = link_to "by registration", "/users/by_registration"
.row
  .col-md-10.all-users
    - @users.each do |user|
      article.user id="user_#{user.id}"
        .user-avatar
          = link_to user_path(user) do
            = image_tag user.avatar.medium.url
        .user-info
          = link_to user.username, user_path(user)
          div
            small
              = user.location
          div
            strong
              = user.reputation_sum
    .clearfix
    = paginate @users
  .col-md-2
    = link_to "Ask a Question", new_question_path, class: "btn btn-primary ask-question"

app/views/users/logins.html.slim
= render "navigation"
.row
  .col-md-12
    ul
      - User.omniauth_providers.each do |provider|
        li
          - if @user.identities.find_by(provider: provider.to_s)
            |#{provider.to_s.titleize} account already added
          - else
            = link_to "Add #{provider.to_s.titleize} account", omniauth_authorize_path(@user, provider)

app/views/users/show.html.slim
= render "navigation"
.row
  .col-md-6.row.user-info
    .col-md-4
      img.user-avatar src=(@user.avatar.small.url)
    .col-md-8
      table.table
        tr
          td
            strong Username
          td
            span = @user.username
        tr
          td
            strong Reputation
          td
            span.user-reputation
              = @user.reputation_sum
        tr
          td
            strong Registered
          td
            span.user-registered
              = @user.created_at.strftime("%d/%m/%Y %H:%M")
        tr
          td
            strong Email
          td
            span.user-email
              = @user.email
        - unless @user.website.blank?
          tr
            td
              strong Website
            td
              span.user-website
                = @user.website
        - unless @user.location.blank?
          tr
            td
              strong Location
            td
              span.user-location
                = @user.location
        - unless @user.age.blank?
          tr
            td
              strong Age
            td
              span.user-age
                = @user.age
        - unless @user.full_name.blank?
          tr
            td
              strong Full name
            td
              span.user-full-name
                = @user.full_name
  .col-md-6
.row
  .col-md-12
    ul.nav.nav-tabs.user-profile-tabs
      li
        a href="#" summary
      li
        a href="#" favorites
      li
        a href="#" questions
      li
        a href="#" answers
      li
        a href="#" comments

.row.user-summary.pane
  .col-md-6
    h3.user-questions
      - if @user.questions.count > 5
        |  Last 5 Questions
        span.text-muted
          |  (total #{@user.questions.count})
      - else
        | #{pluralize(@user.questions.count, 'Question')}
    ul.created-questions
      - @user.questions.limit(5).each do |question|
        li
          span.votes
            = question.votes_sum
          = link_to question.title, question_path(question)
    h3.user-answers
      - if @user.answers.count > 5
        |  Last 5 Answers
        span.text-muted
          |  (total #{@user.answers.count})
      - else
        | #{pluralize(@user.answers.count, 'Answer')}
    ul.created-answers
      - @user.answers.limit(5).each do |answer|
        li
          span.votes
            = answer.votes_sum
          = link_to answer.body, url_for(answer.question) + "#answer_#{answer.id}", class: "#{answer.best? ? 'best' : ''}"
  .col-md-6
    h3.user-reputation #{@user.reputation_sum} Reputation
    - if @user.reputation_sum > 0
      #reputation-chart
        - @user.reputations_chart_data.each do |rep|
          .reputation-column-outer title="#{rep[:date].strftime('%A, %d %B %Y')}, #{rep[:reputation]} reputation"
            .reputation-column-inner style="height: #{rep[:percentage]}%"

    h3.user-comments
      - if @user.comments.count > 5
        |  Last 5 Comments
        span.text-muted
          |  (total #{@user.comments.count})
      - else
        | #{pluralize(@user.comments.count, 'Comment')}
    ul.created-comments
      - @user.comments.limit(5).each do |comment|
        li
          span.votes
            = comment.votes_sum
          = link_to comment.body, url_for(comment.commentable.respond_to?(:question) ? comment.commentable.question : comment.commentable) + "#comment_#{comment.id}"

.row.user-favorites.pane
  .col-md-12
    h3.favorite-questions
      | #{pluralize(@user.favorite_questions.count, 'Favorite Question')}
    table.created-questions.table
      - @user.favorites.each do |question|
        tr
          td.votes
            = question.votes_sum
          td
            = link_to question.title, question_path(question)
          td.text-right
            = question.created_at.strftime("%d/%m/%Y %H:%M")

.row.user-all-questions.pane
  .col-md-12
    h3.user-questions
      | #{pluralize(@user.questions.count, 'Question')}
    table.created-questions.table
      - @user.questions.each do |question|
        tr
          td.votes
            = question.votes_sum
          td
            = link_to question.title, question_path(question)
          td.text-right
            = question.created_at.strftime("%d/%m/%Y %H:%M")
.row.user-all-answers.pane
  .col-md-12
    h3.user-answers
      | #{pluralize(@user.answers.count, 'Answer')}
    table.created-answers.table
      - @user.answers.each do |answer|
        tr
          td.votes
            = answer.votes_sum
          td
            = link_to answer.body, url_for(answer.question) + "#answer_#{answer.id}", class: "#{answer.best? ? 'best': ''}"
          td.text-right
            = answer.created_at.strftime("%d/%m/%Y %H:%M")
.row.user-all-comments.pane
  .col-md-12
    h3.user-comments
      | #{pluralize(@user.comments.count, 'Comment')}
    table.created-comments.table
      - @user.comments.each do |comment|
        tr
          td.votes
            = comment.votes_sum
          td
            = link_to comment.body, url_for(comment.commentable.respond_to?(:question) ? comment.commentable.question : comment.commentable) + "#comment_#{comment.id}"
          td.text-right
            = comment.created_at.strftime("%d/%m/%Y %H:%M")