config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :commentable do
    resources :comments, only: [:create, :edit, :update, :destroy], concerns: :votable
  end

  concern :votable do
    patch :vote_up, on: :member, controller: :votes
    patch :vote_down, on: :member, controller: :votes
  end

  resources :questions, concerns: [:commentable, :votable], shallow: true do
    resources :answers, only: [:new, :create, :edit, :update, :destroy],
                        shallow: true,
                        concerns: [:commentable, :votable] do
      post "mark_best", on: :member
    end

    collection do
      get "popular(/page/:page)" => "questions#popular", as: :popular
      get "unanswered(/page/:page)" => "questions#unanswered", as: :unanswered
      get "active(/page/:page)" => "questions#active", as: :active
      get "tagged/:tag(/page/:page)" => "questions#tagged", as: :tagged
    end

    post "add_favorite" => "questions#add_favorite", as: :add_favorite
    post "remove_favorite" => "questions#remove_favorite", as: :remove_favorite
  end

  resources :tags, only: :index do
    collection do
      get "/(page/:page)", to: "tags#index"
      get "/newest(/page/:page)", to: "tags#newest", as: :newest
      get "/popular(/page/:page)", to: "tags#popular", as: :popular
    end
  end

  resources :attachments, only: [:destroy]

  resources :users, only: [:index, :show, :edit, :update], param: :username do
    get "/logins" => "users#logins", as: :logins, on: :member

    collection do
      get "/by_registration(/page/:page)", to: "users#by_registration", as: :by_registration
      get "/alphabetically(/page/:page)", to: "users#alphabetically", as: :alphabetically
    end
  end

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
      resources :users, only: [:index, :show], param: :username
      get "/profile", to: "users#profile", as: :profile
    end
  end

  root "questions#index"
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  question_id :integer
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  best        :boolean          default(FALSE)
#

class Answer < ApplicationRecord
  include Votable

  default_scope { order("best DESC, votes_sum DESC, created_at ASC") }

  belongs_to :question, counter_cache: true
  belongs_to :user

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy

  accepts_nested_attributes_for :attachments, reject_if: :no_attachment

  validates :body, presence: true, length: { in: 10..5000 }

  after_save :update_question_activity
  after_create :send_notification

  def mark_best!
    return if question.best_answer?
    update(best: true)
    Reputation.add_to(user, :answer_mark_best)
  end

  def notify_subscribers
    question&.favorites&.find_each do |fuser|
      AnswerMailer.new_for_subscribers(fuser, question).deliver
    end
  end

  private

  def update_question_activity
    question.save
  end

  def no_attachment(attrs)
    attrs["file"].blank? && attrs["file_cache"].blank?
  end

  def send_notification
    delay.notify_subscribers
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:create]
  before_action :set_answer, except: :create
  before_action :add_user_id_to_attachments, only: [:create, :update]
  after_action :publish, only: [:create, :destroy], unless: -> { Rails.env.production? }
  after_action :update_edited, only: :update

  respond_to :json

  authorize_resource

  def create
    @comment = Comment.new
    respond_with @answer = @question.answers.create(answer_params.merge(user_id: current_user.id))
  end

  def update
    update_resource @answer
  end

  def destroy
    respond_with @answer.destroy
  end

  def mark_best
    @answer.mark_best!
    flash[:success] = "Answer marked as best!"
    redirect_to @answer.question
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :file_cache, :user_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def publish
    case params[:action]
    when "create"
      if @answer.valid?
        PrivatePub.publish_to "/questions/#{@answer.question.id}",
                              answer_create: AnswerSerializer.new(@answer, root: false).to_json
      end
    when "destroy"
      PrivatePub.publish_to "/questions/#{@answer.question.id}", answer_destroy: @answer.id
    end
  end

  def update_edited
    @answer.update(edited_at: Time.zone.now) unless @answer.errors.any?
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def index
    @question = Question.find(params[:question_id])
    respond_with @answers = @question.answers
  end

  def show
    respond_with @answer = Answer.find(params[:id])
  end

  def create
    @question = Question.find(params[:question_id])
    respond_with @answer = @question.answers.create(answer_params.merge(user_id: current_resource_owner.id))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
article id="answer_#{answer.id}" class="answer panel panel-default #{"best-answer" if answer.best?}"
  .panel-body
    .row
      .col-md-1.answer-voting
        .voting
          - if can?(:vote_up, answer)
            = link_to "", vote_up_answer_path(answer), class: "vote-up", remote: true, data: { type: :json }, method: :patch
          - elsif answer.user_voted(current_user) == 1
            span.voted-up
          strong.votes = answer.votes_sum
          - if can?(:vote_down, answer)
            = link_to "", vote_down_answer_path(answer), class: "vote-down", remote: true, data: { type: :json }, method: :patch
          - elsif answer.user_voted(current_user) == -1
            span.voted-down
      .col-md-11
        .answer-body
          = answer.body
    .answer-author.text-right
      small
        | by
        = link_to answer.user.username, user_path(answer.user.username)
        |  #{time_ago_in_words(answer.created_at)} ago
      div
        img src=(answer.user.avatar.tiny.url)
        br
        small
          = answer.user.reputation_sum
      - if answer.edited_at.to_s > answer.created_at.to_s
        small
          span.text-muted
            | edited
            = time_ago_in_words(answer.edited_at)
            |  ago
    - if answer.attachments.any?
      ul.answer-attachments.attachments-list
        - answer.attachments.each do |a|
          li
            div
              a href="#{a.file.url}" rel="shadowbox[answer#{answer.id}-attachments]"
                = image_tag a.file.url
              - if can?(:destroy, a)
                = link_to a, method: :delete, data: {confirm: "Are you sure?", remote: true}, class: "delete-attachment" do
                  span.glyphicon.glyphicon-remove
    .comments-wrapper
      - if answer.comments.size > 0
        ul.comments
          = render answer.comments
  .panel-footer
    ul.answer-management
      - if can?(:mark_best, answer)
        li
          = link_to [:mark_best, answer], class: "mark-best-answer", method: :post do
            span.glyphicon.glyphicon-ok
      - if can?(:edit, answer)
        li
          = link_to "#", class: "edit-answer" do
            span.glyphicon.glyphicon-pencil
        li
          = link_to answer, remote: true, class: "delete-answer", id: "delete-answer", method: :delete, data: { confirm: "Are you sure?", id: answer.id } do
            span.glyphicon.glyphicon-remove
      - if can?(:create, Comment)
        li
          = link_to "Comment", "#", class: "show-comment-form"
    .comment-form
      = render "comments/form", comment: Comment.new, commentable: answer

app/views/answers/_attachment_fields.html.slim
.nested-fields.row
  .col-md-10
    - if f.object.file?
      div
        strong
          = f.object.file.filename
    = f.input :file, label: false
    = f.hidden_field :file_cache
  .col-md-2
    = link_to_remove_association "Remove file", f

app/views/answers/_form.html.slim
= simple_form_for [(@question || answer.question), answer], remote: true, data: { type: :json }, html: { id: "answer-form" } do |f|
  = f.error_notification
  = f.input :body, input_html: { rows: 10 }, label: false
  = f.simple_fields_for :attachments, answer.attachments.build do |a|
    = a.label :files
    |&nbsp;&nbsp;&nbsp;
    = link_to_add_association 'Add file', f, :attachments, data: {"association-insertion-node" => ".nested-fields:last", "association-insertion-method" => "after"}
    = render 'attachment_fields', f: a
  .form-group
    = f.button :submit, class: "btn btn-success"